### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by agentzz1** [Vincentt1705/partalert-link-opener#1]
hello the link opener stopped working around yesterday it doesnt open links anymore.

**Comment by Vincentt1705** [comment]
Hey, I’m aware that the link opener stopped working. This is an issue with the discord api not recognizing embeds anymore since yesterday. There’s nothing I can do about it for the discord link opener.

**Comment by Vincentt1705** [comment]
Decided to do include the workaround so script should now work fine again.
